### ISSUE TITLE
regexp-replace opens a terminal window

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#5]
closing the window kills DrRacket,.

<img width="644" alt="rreplace" src="https://user-images.githubusercontent.com/108047/33179578-cb949d82-d061-11e7-847a-86204dbfedd3.PNG">

**Comment by Metaxal** [comment]
Hey Stephen,

Thanks for all the feedback.

On Ubuntu, I don't see this behaviour. Windows-specific?

Also, I don't see why it would do that. Can you try the following:
- Open the script file with "Scripts > Manage Scripts > Open Script ..."
then choose "regexp-replace.rkt"
- Surround line 70 with 'gui-utils:ok' with a '(void ....)' to make sure
nothing is output to the console
- Save the file
- Try to use regexp-replace again and see if the terminal pops up again.

Thanks!

**Comment by spdegabrielle** [comment]
Must be windows. I'll try MacOS tonight when I get home.

I followed your instruction but got the same issue.

![image](https://user-images.githubusercontent.com/108047/33182513-40a806ae-d06c-11e7-8444-2d8b4b7c87e1.png)

**Comment by Metaxal** [comment]
Oh I think I know what it is:
What you see is DrRacket's console. The console shows up on Windows as soon
as something is displayed to the stdout port. DrRacket is probably careful
to not output anything.

Anyway, there's one more void to add: On line 20, surround the '(new
message% ....)' expression with '(void ....)'. I think that should fix it.

**Comment by spdegabrielle** [comment]
getting some different errors now
![image](https://user-images.githubusercontent.com/108047/33187547-6ed04ba4-d08a-11e7-9b87-00093efd4d5a.png)

and 

![image](https://user-images.githubusercontent.com/108047/33187572-9c200e78-d08a-11e7-8838-6857feddf3e9.png)

**Comment by Metaxal** [comment]
Ah right. For the second issue, it's because gui-utils:ok/cancel-buttons
returns two values.
Around line 70, replace the '(void ....)' with
(define-values (_a _b) ....)
so as the receive the two values and avoid displaying them in the terminal.

Regarding the first error, that is quite strange. When does this error
appear?

**Comment by Metaxal** [comment]
I think my last push should fix your problem (once it gets sync'ed on the pkg server). Because the personal scripts are kept untouched, you may want to overwrite your regexp-replace.rkt script with the 'bundled' one. To do this, simply click on "Scripts > Manage Scripts > Import bundled script...", then choose regexp-replace.rkt and confirm the overwrite.

Let me know if this fixes the issue. I'm keeping this issue open in the meantime.

If you have any other comment/issue about the script plugin, please share :) As you can see there aren't many comments yet apart from yours.

**Comment by spdegabrielle** [comment]
Sorry have been busy. Thank you very much for you help. I'll test this shortly.

**Comment by Metaxal** [comment]
Did you try this one by any chance? No worries if you don't have time of course.

**Comment by spdegabrielle** [comment]
tested on MacOS - looks good now!

**Comment by Metaxal** [comment]
Excellent, thanks for testing! I believe it's fixed for Windows too, but if you happen to see that again don't hesitate to re-open this issue.

**Comment by spdegabrielle** [comment]
and fine on Window 8!
